# Generated by Django 5.0.4 on 2024-06-20 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumParametrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_no2', models.PositiveSmallIntegerField(default=0)),
                ('maximum_no2', models.PositiveSmallIntegerField(default=10)),
                ('too_low_no2_hint', models.CharField(max_length=100)),
                ('too_high_no2_hint', models.CharField(max_length=100)),
                ('minimum_no3', models.PositiveSmallIntegerField(default=0)),
                ('maximum_no3', models.PositiveSmallIntegerField(default=10)),
                ('too_low_no3_hint', models.CharField(max_length=100)),
                ('too_high_no3_hint', models.CharField(max_length=100)),
                ('minimum_gh', models.PositiveSmallIntegerField(default=0)),
                ('maximum_gh', models.PositiveSmallIntegerField(default=10)),
                ('too_low_gh_hint', models.CharField(max_length=100)),
                ('too_high_gh_hint', models.CharField(max_length=100)),
                ('minimum_kh', models.PositiveSmallIntegerField(default=0)),
                ('maximum_kh', models.PositiveSmallIntegerField(default=10)),
                ('too_low_kh_hint', models.CharField(max_length=100)),
                ('too_high_kh_hint', models.CharField(max_length=100)),
                ('minimum_ph', models.PositiveSmallIntegerField(default=0)),
                ('maximum_ph', models.PositiveSmallIntegerField(default=10)),
                ('too_low_ph_hint', models.CharField(max_length=100)),
                ('too_high_ph_hint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField(default=10)),
                ('min_volume', models.PositiveSmallIntegerField(default=20)),
                ('max_volume', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField(default=10)),
                ('min_volume', models.PositiveSmallIntegerField(default=20)),
                ('max_volume', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField(default=10)),
                ('min_volume', models.PositiveSmallIntegerField(default=20)),
                ('max_volume', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('z', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('decorators', models.ManyToManyField(blank=True, to='AquaMaker.decorator')),
                ('filters', models.ManyToManyField(blank=True, to='AquaMaker.filter')),
                ('heater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.heater')),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.light')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.pump')),
            ],
        ),
    ]
