# Generated by Django 5.0.4 on 2024-06-18 17:36

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField(default=10)),
                ('min_volume', models.PositiveSmallIntegerField(default=20)),
                ('max_volume', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField(default=10)),
                ('min_volume', models.PositiveSmallIntegerField(default=20)),
                ('max_volume', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField(default=10)),
                ('min_volume', models.PositiveSmallIntegerField(default=20)),
                ('max_volume', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('z', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('decorators', models.ManyToManyField(blank=True, to='AquaMaker.decorator')),
                ('filters', models.ManyToManyField(blank=True, to='AquaMaker.filter')),
                ('heater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.heater')),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.light')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.pump')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAquarium',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('z', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('heater', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AquaMaker.heater')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('light', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AquaMaker.light')),
                ('pump', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AquaMaker.pump')),
            ],
            options={
                'verbose_name': 'historical aquarium',
                'verbose_name_plural': 'historical aquariums',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAquarium_filters',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('aquarium', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AquaMaker.aquarium')),
                ('filter', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AquaMaker.filter')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='AquaMaker.historicalaquarium')),
            ],
            options={
                'verbose_name': 'HistoricalAquarium_filters',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
