# Generated by Django 5.0.4 on 2024-05-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaMaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='heater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.heater'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='light',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.light'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.pump'),
        ),
    ]
