# Generated by Django 5.0.4 on 2024-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaMaker', '0002_alter_aquarium_heater_alter_aquarium_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heater',
            name='max_volume',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='heater',
            name='min_volume',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='light',
            name='max_volume',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='light',
            name='min_volume',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='pump',
            name='max_volume',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='pump',
            name='min_volume',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='heater',
            name='power',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='light',
            name='power',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pump',
            name='power',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
