# Generated by Django 5.0.4 on 2024-06-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaMaker', '0002_alter_aquarium_heater_alter_aquarium_light_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aquarium',
            name='decorators',
            field=models.ManyToManyField(blank=True, to='AquaMaker.decorators'),
        ),
    ]
