# Generated by Django 5.0.4 on 2024-06-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AquaMaker', '0003_decorators_aquarium_decorators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decorators',
            new_name='Decorator',
        ),
    ]
