# Generated by Django 5.0.4 on 2024-06-09 17:17

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaMaker', '0003_historicalaquarium'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAquarium_filters',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('aquarium', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AquaMaker.aquarium')),
                ('filter', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AquaMaker.filter')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='AquaMaker.historicalaquarium')),
            ],
            options={
                'verbose_name': 'HistoricalAquarium_filters',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
