# Generated by Django 5.0.4 on 2024-06-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AquaMaker', '0003_heater_max_volume_heater_min_volume_light_max_volume_and_more'),
        ('AquaMaker', '0004_rename_decorators_decorator'),
    ]

    operations = [
    ]
