# Generated by Django 5.0.4 on 2024-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaMaker', '0005_merge_20240614_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumParametrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_no2', models.PositiveSmallIntegerField(default=0)),
                ('maximum_no2', models.PositiveSmallIntegerField(default=10)),
                ('too_low_no2_hint', models.CharField(max_length=100)),
                ('too_high_no2_hint', models.CharField(max_length=100)),
                ('minimum_no3', models.PositiveSmallIntegerField(default=0)),
                ('maximum_no3', models.PositiveSmallIntegerField(default=10)),
                ('too_low_no3_hint', models.CharField(max_length=100)),
                ('too_high_no3_hint', models.CharField(max_length=100)),
                ('minimum_gh', models.PositiveSmallIntegerField(default=0)),
                ('maximum_gh', models.PositiveSmallIntegerField(default=10)),
                ('too_low_gh_hint', models.CharField(max_length=100)),
                ('too_high_gh_hint', models.CharField(max_length=100)),
                ('minimum_kh', models.PositiveSmallIntegerField(default=0)),
                ('maximum_kh', models.PositiveSmallIntegerField(default=10)),
                ('too_low_kh_hint', models.CharField(max_length=100)),
                ('too_high_kh_hint', models.CharField(max_length=100)),
                ('minimum_ph', models.PositiveSmallIntegerField(default=0)),
                ('maximum_ph', models.PositiveSmallIntegerField(default=10)),
                ('too_low_ph_hint', models.CharField(max_length=100)),
                ('too_high_ph_hint', models.CharField(max_length=100)),
            ],
        ),
    ]
