# Generated by Django 5.0.4 on 2024-06-10 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AquaMaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionalSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.aquarium')),
                ('situation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMonitor.situationtype')),
            ],
        ),
        migrations.CreateModel(
            name='WaterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('no2', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('no3', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gh', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('kh', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaMaker.aquarium')),
            ],
        ),
    ]
