# Generated by Django 5.0.4 on 2024-05-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AquaAccount', '0002_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
    ]
